spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: gnos-backend

  ai:
    openai:
      api-key: ${OPENAI_TOKEN}
      chat:
        options:
          model: gpt-4o-mini

  logging:
    level:
      root: INFO                # Set the default logging level for all packages
      com.yourpackage: DEBUG     # Replace 'com.yourpackage' with your actual package name to enable DEBUG level logging for that package
      org.springframework: WARN   # Set Spring framework logging level
      org.hibernate: WARN        # Set Hibernate logging level
