server:
  port: 8081

spring:
  datasource:
    url: {DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true

  application:
    name: gnos-backend

  ai:
    openai:
      api-key: {OPENAI_TOKEN}
      chat:
        options:
          model: gpt-4o-mini
