spring:
  datasource:
    url: jdbc:postgresql://db:5432/quotes_db
    username: admin
    password: secret123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: '0'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: gnos-backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@email.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    openai:
      api-key: 123
      chat:
        options:
          model: gpt-4o-mini

  jwt:
    secret: 123
    expiration: 3600000
